commands:
    - sudo python setup.py develop
    - py.test
    - sphinx-build -b html ./docs /var/www/docs/typeschema/ > /dev/null
    - mkdir -p /var/www/coverage/typeschema
    - py.test --cov=. --cov-report=html && mv htmlcov/* /var/www/coverage/typeschema/`git rev-parse --abbrev-ref HEAD`/

environment:
  language: java

build:
  checkout:
    - echo "Skippped"
  info:
    - echo "Skippped"
  run:
    - echo "Skippped"
